import Head from 'next/head'
import Footer from '../components/footer.js'
import styles from '../styles/Home.module.css'
import Toolbar from '../components/toolbar.js'
import Card from '../components/card.js'
import data from '../data/data.ts'

export default function Home() {
  return (    
    <div className={styles.container}>
      <Toolbar/>
      <Head>
        <title>NSB Cards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/clean_manyBruces.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          
          Welcome to <a href="https://nextjs.org">NSB Gang</a>
        </h1> 

        <p className={styles.description}>
          Email{' '}
          <code className={styles.code}>andrewblackmore95@gmail.com</code>
          {' '}to add more cards
        </p>

        <div className={styles.grid}>
          <img className={styles.img} src="/clean_manyBruces.png"></img>
        </div>
        <Card id='0' name={data}/>
      </main>
      <Footer/>
      
    </div>
  )
}
